<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <Description>ToolGet is a tool which makes it easy to search and install dotnet tools.</Description>
    <Company>Iciclecreek</Company>
    <Authors>Tom Laird-McConnell</Authors>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ToolGet</ToolCommandName>
    <PackageId>ToolGet</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/tomlm/ToolGet</PackageProjectUrl>
    <PackageIconUrl>https://raw.githubusercontent.com/tomlm/ToolGet/master/icon.png</PackageIconUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/tomlm/ToolGet</RepositoryUrl>
    <Copyright>Tom Laird-McConnell All Rights Reserved</Copyright>
    <RootNamespace>ToolGet.Console</RootNamespace>
    <ContentTargetFolders>content</ContentTargetFolders>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="" />
    <None Include="../../icon.png" Pack="true" PackagePath="" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Consolonia" Version="11.3.4-beta.1604" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ToolGet.Core/ToolGet.Core.csproj" />
  </ItemGroup>

</Project>
